name = "private-folio"
compatibility_date = "2024-12-05"
compatibility_flags = ["nodejs_compat"]
main = "src/index.ts"
assets = { directory = "dist", binding = "ASSETS" }

[observability]
[observability.logs]
enabled = false
head_sampling_rate = 1
invocation_logs = true
persist = true

[define]
__dirname = "'/'"
"process.env" = "{}"

[[d1_databases]]
binding = "DB"
database_name = "portfolio-db"
database_id = "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx" # Placeholder for local dev
