name = "private-folio"
compatibility_date = "2024-12-05"
main = "src/index.ts"
assets = { directory = "dist", binding = "ASSETS" }

[[d1_databases]]
binding = "DB"
database_name = "portfolio-db"
database_id = "" # User to fill
